# Generated by Django 3.0.4 on 2020-03-13 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=25)),
                ('zip_code', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': ('address',),
                'verbose_name_plural': ('addresses',),
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': ('employee',),
                'verbose_name_plural': ('employees',),
                'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('user.date_joined'), nulls_last=True),),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('serial_number', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('storage_location', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='supplymateapi.Address')),
            ],
            options={
                'verbose_name': ('item',),
                'verbose_name_plural': ('items',),
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': ('item_type',),
                'verbose_name_plural': ('item_types',),
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': ('role',),
                'verbose_name_plural': ('roles',),
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': ('status',),
                'verbose_name_plural': ('statuses',),
            },
        ),
        migrations.CreateModel(
            name='SupplyRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date_time', models.DateTimeField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='supplymateapi.Address')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='supplymateapi.Employee')),
            ],
            options={
                'verbose_name': ('supply_request',),
                'verbose_name_plural': ('supply_requests',),
            },
        ),
        migrations.CreateModel(
            name='SupplyRequestItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='supplymateapi.Item')),
                ('supply_request', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='supplymateapi.SupplyRequest')),
            ],
            options={
                'verbose_name': ('supply_request_item',),
                'verbose_name_plural': ('supply_request_items',),
            },
        ),
        migrations.AddField(
            model_name='supplyrequest',
            name='items',
            field=models.ManyToManyField(through='supplymateapi.SupplyRequestItem', to='supplymateapi.Item'),
        ),
        migrations.AddField(
            model_name='supplyrequest',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='supplymateapi.Status'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='supplymateapi.ItemType'),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='supplymateapi.Role'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
