# Generated by Django 3.0.4 on 2020-03-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplymateapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': ('employee',), 'verbose_name_plural': ('employees',)},
        ),
        migrations.AddField(
            model_name='supplyrequestitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
