# Generated by Django 3.0.4 on 2020-03-24 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplymateapi', '0002_auto_20200324_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplyrequestitem',
            old_name='quantity',
            new_name='requested_quantity',
        ),
    ]
